### ISSUE TITLE
Router swap error for ETH/SDT pair on Brave Browser only

### ISSUE THREAD

**Issue by amytsang** [curvefi/curve-frontend#346]
![Image](https://github.com/user-attachments/assets/fdcab1e1-3ba6-4d66-9c87-d0599e617e40)
seems UI brokes when type "from" amount for example .10 or .20 or .001, this happens on swap router page / also on pool>swap pages
and not only on Brave browser / nor with specific tokens
![Image](https://github.com/user-attachments/assets/650abbe5-020d-4cd4-be5a-8d9c1049727b)
error on console 
![Image](https://github.com/user-attachments/assets/bb428077-06b7-489d-9597-cc8238f6de78)

![Image](https://github.com/user-attachments/assets/88e1a004-b94f-4a03-8cd0-124c1f1fa221)

**Comment by ignromanov** [comment]
#357
